# Generated by Django 4.0.4 on 2022-07-31 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Имя города', help_text='<small class="text-muted">Имя страны</small><hr><br>', max_length=254, unique=True, verbose_name='Имя города:')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Имя страны', help_text='<small class="text-muted">Имя страны</small><hr><br>', max_length=254, unique=True, verbose_name='Имя страны:')),
            ],
        ),
        migrations.DeleteModel(
            name='IceCreamCategory',
        ),
        migrations.RemoveField(
            model_name='icecreamlike',
            name='user',
        ),
        migrations.DeleteModel(
            name='IceCreamComment',
        ),
        migrations.DeleteModel(
            name='IceCreamLike',
        ),
        migrations.AddField(
            model_name='city',
            name='country_id',
            field=models.ForeignKey(blank=True, db_column='country_db_column', db_tablespace='country_db_tablespace', default=None, error_messages=False, help_text='<small class="text-muted">Из какой страны</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_student.country', unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Из какой страны'),
        ),
    ]
