# Generated by Django 4.0.4 on 2022-08-01 19:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_teacher', '0016_alter_receiptcomment_options_receipt_instructions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receiptcomment',
            options={'ordering': ('receipt',), 'verbose_name': 'Комментарий к рецепту', 'verbose_name_plural': 'Комментарии к рецептам'},
        ),
        migrations.RemoveField(
            model_name='receiptcomment',
            name='create',
        ),
        migrations.RemoveField(
            model_name='receiptcomment',
            name='time',
        ),
        migrations.RemoveField(
            model_name='receiptcomment',
            name='update',
        ),
        migrations.RemoveField(
            model_name='receiptrating',
            name='is_liked',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='image',
            field=models.ImageField(blank=True, default='img/receipt/default/default_receipt.jpg', help_text='<small class="text-muted">это наша заставка</small><hr><br>', null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])], verbose_name='Заставка:'),
        ),
        migrations.AlterField(
            model_name='receiptrating',
            name='receipt',
            field=models.ForeignKey(blank=True, default=None, error_messages=False, help_text='<small class="text-muted">Рецепт</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_teacher.receipt', unique_for_date=False, unique_for_month=False, unique_for_year=False, verbose_name='Рецепт'),
        ),
    ]
